version: '3'

services:
  dashboard:
    image: portainer/portainer
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    ports:
      - "9000:9000"

  webapi:
    image: ninjafx/eq-webapi:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8003:8003"
    depends_on:
      - db
      - elk

  web:
    image: ninjafx/eq-web:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8002:8002"
    depends_on:
      - db
      - elk

  db:
    image: ninjafx/eq-database:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: testuser123!
    ports:
      - "1433:1433"

  elk:
    image: nshou/elasticsearch-kibana
    ports:
      - 9200:9200
      - 5601:5601