USE [master]
GO
/****** Object:  Database [Equinox]    Script Date: 14/12/2016 05:20:46 ******/
CREATE DATABASE [Equinox]
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Equinox].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Equinox] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [Equinox] SET ANSI_NULLS OFF
GO
ALTER DATABASE [Equinox] SET ANSI_PADDING OFF
GO
ALTER DATABASE [Equinox] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [Equinox] SET ARITHABORT OFF
GO
ALTER DATABASE [Equinox] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [Equinox] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [Equinox] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [Equinox] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [Equinox] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [Equinox] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [Equinox] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [Equinox] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [Equinox] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [Equinox] SET  ENABLE_BROKER
GO
ALTER DATABASE [Equinox] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [Equinox] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [Equinox] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [Equinox] SET ALLOW_SNAPSHOT_ISOLATION ON
GO
ALTER DATABASE [Equinox] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [Equinox] SET READ_COMMITTED_SNAPSHOT ON
GO
ALTER DATABASE [Equinox] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [Equinox] SET RECOVERY FULL
GO
ALTER DATABASE [Equinox] SET  MULTI_USER
GO
ALTER DATABASE [Equinox] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [Equinox] SET DB_CHAINING OFF
GO
USE [Equinox]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 14/12/2016 05:20:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[StoredEvent]    Script Date: 14/12/2016 05:20:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[StoredEvent](
	[Id] [uniqueidentifier] NOT NULL,
	[AggregateId] [uniqueidentifier] NOT NULL,
	[Data] [nvarchar](max) NULL,
	[Action] [varchar](100) NULL,
	[CreationDate] [datetime2](7) NOT NULL,
	[User] [nvarchar](max) NULL,
 CONSTRAINT [PK_StoredEvent] PRIMARY KEY CLUSTERED
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO
create table Equinox.dbo.Products
(
	Id uniqueidentifier not null
		constraint Products_Id_pk
			primary key,
	Name varchar(100) not null,
	LastUpdateDate datetime
)
go

create unique index Products_Id_uindex
	on Products (Id)
go
