version: '3'

services:
  webapi:
    image: ninjafx/eq-webapi:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8003:8003"
    networks:
      - webnet
    depends_on:
      - db

  web:
    image: ninjafx/eq-web:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8002:8002"
    networks:
      - webnet
    depends_on:
      - db

  db:
    image: ninjafx/eq-database:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: testuser123!
    ports:
      - "1433:1433"
    networks:
      - webnet

networks:
  webnet: